services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    workingDir: backend
    pythonVersion: 3.10
    autoDeploy: true
